### ISSUE TITLE
Plan a dream Vacation to a set of stadiums

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#10]
As a baseball fan, I want to be able to plan a trip to visit a selection of stadiums starting at the stadium of my choice using the shortest path possible. 
### Tasks
- [x] Implement Dijkstra’s algorithm #29 
- [x] Display results in the GUI #31
- [x] Allow the baseball fan to choose a starting point #31
- [x] Allow the baseball fan to select the stadiums to visit #31
### Definition Of Done
- [x] use Dijkstra’s algorithm 
- [ ] Algorithm produces the shortest route
- [x] Algorithm can use any stadium as input
- [ ] Algorithm can use any stadium as a starting point
- [x] Algorithm only uses stadiums selected by the user
- [ ] Display the final route , stadiums visited and in what order, and total mileage in the GUI
### Test Scenarios
- Need test scenarios
