### ISSUE TITLE
Calculate the minimum spanning tree

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#11]
As a baseball manager, I want to be able to calculate the minimum spanning tree that connects all major league stadiums. 
### Tasks
- [x] Implement the minimum spanning tree algorithm using Prim or Kruskal #30 
- [x] Calculate the minimum spanning tree
- [ ] Display the minimum spanning tree and the total milage in the GUI
### Definition Of Done
- [ ] The minimum spanning tree is calculated correctly and with the correct milage
- [ ] Display the minimum spanning tree and total mileage in the GUI
### Test Scenarios
- Need test scenarios
