### ISSUE TITLE
souvenir shopping cart

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#12]
As a baseball fan, I want to be able to access my shopping cart at any time while taking a trip, so that I can keep track of the items I am purchasing.
### Description

Only during taking a trip, a baseball fan is able to purchase souvenirs. The shopping cart will be updated instantly once an item is added to cart. The user should be able to press the shopping cart icon/button and a shopping cart interface should appear. The shopping cart should display what souvenirs have been bought from what stadiums and grand total spent at each individual stadium. There should also be a grand total of what the baseball fan has spent at all stadiums. Once baseball fan purchases their item, however much spent at each stadium must be added to stadium's total revenue.
### Tasks
- [ ] Create an interface to display baseball fan's cart. #32
- [ ] Restrict shopping cart to be only seen while taking a trip, and at the end to confirm purchases.
### Definition of Done
- [ ] The Cart keeps track up purchases and money spent during the trip
- [ ] the cart displays the items purchased and the money spent  in the GUI
### Test Scenarios
- Check if all total price for each stadium is correct.
- Create test data, and ensure subtotal and grand total are correct.
