### ISSUE TITLE
Be able to modify the souvenirs list

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#13]
As a baseball manager, I to be able to add, delete, or change items in the list of souvenirs as well as change any items price
### Tasks
- [ ] Implement a easy to use and attractive interface for editing items
- [ ] Make changes to the items persistent
- [ ] Be able to add or delete items from the list of souvenirs
- [ ] Be able to change an item in the list of souvenirs, including price
### Definition Of Done
- [ ] The GUI interface is attractive and easy to use
- [ ]  changes to items are persistent
- [ ] changes to items DOES NOT affect past purchase data
- [ ] feature is only accessible by an admin user
### Test Scenarios
- Need test scenarios
