### ISSUE TITLE
Be able to add new stadiums and teams

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#16]
As a baseball manager, I want be able to add new teams and their corresponding stadium if the major leagues decides to add a new team.
### Tasks
- [ ] implement an attractive and easy to use GUI interface
- [ ] Add the ability to add a new baseball team with an associated stadium
- [ ] Ability to link the new stadium to the other existing stadiums
- [ ] The changes need to be persistent
### Definition Of Done
- [ ] the gui interface is attractive and easy to use
- [ ] only an admin user can add a new baseball team and associated stadium
- [ ] Added teams and stadiums are persistent
- [ ] Any new teams and stadiums are taken into account during all algorithms
- [ ] feature is only accessible by an admin user
### Test Scenarios
- Need test scenarios
