### ISSUE TITLE
add and delete souveniers

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#17]
As a national baseball league manager, I want the ability to add a new souvenir to a specific stadium.
### Description

First, the admin should be able to select a specific stadium that they desire to add a new souvenir to. Once, a stadium is selected, the admin should be able to add/input a new souvenir to a specific stadium's souvenir list. Once added, the database and program should be updated instantly, and the item can now be viewed by admin and baseball fan. Each stadium should have access to the newly added item. 
### Tasks
- [ ] Create friendly interface page that allows a user to input their new stadium. 
- [ ] Needed text fields: name and price of the new souvenir.
- [ ] Error checking for all inputs.
### Definition of Done
- The admin is able to create data for a new item and added to the database.
- All text fields or inputs are error checked.
- Properly document each method for Doxygen. 
### Test Scenarios
- Check if database updates add new souvenir instantly.
- Check that souvenir item is added to the correct stadium.
- Check if souvenir name and price are correct.
### Story Points (2)

This task is 2 points because due to our test plan, we have designed and implemented already needed methods for this task. Therefore, all that is needed is creating the GUI and calling the methods.
