### ISSUE TITLE
change attributes of souvenir

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#19]
As a national baseball league manager, I want the ability to update a souvenir from a specific stadium, in case I want to change the price or name of a souvenir.
### Description

First, the admin should be able to select a specific stadium that they desire to potentially update a souvenir from. Once, a stadium is selected, the admin should be able to select a souvenir that they want to update. Once updated, the database and program should be updated instantly, and the item will be now updated.
### Tasks
- [ ]  Create friendly interface page that allows a user to select the item they want to update.
- [ ] Textfield needed: name and price of souvenir.
- [ ] All inputs fields should be error checked.
### Definition of Done
- The admin is able to update the item properly.
- Once item is updated, the application must be updated instantly.
- Error checking for all inputs fields.
- The admin is able to change data for an item and add changes to the data base.
- Properly document each method for Doxygen.
### Test Scenarios
- Check if database updates the souvenir's information instantly.
- Check that souvenir item is updated for the correct stadium.
### Story Points (2)

This task is 2 points because due to our test plan, we have designed and implemented already needed methods for this task. Therefore, all that is needed is creating the GUI and calling the methods.
