### ISSUE TITLE
Sort and filter stadium by various criteria

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#2]
As a major league baseball manager, I want to have admin and baseball fans be able to view a list of stadiums sorted/view by multiple ways. 
### Tasks

Administration and baseball fans have the ability to sort/view by:
- [ ] create a list of the major league stadiums by name in alphabetical order
- [ ] create a list of major league stadiums sorted by team name
- [ ] create a list of American League stadiums sorted by team name.
- [ ] create a list of National League stadiums sorted by team name.
- [ ] create a list of stadiums that have a grass surface sorted by team name
- [ ] create a list of stadiums in chronological order by date opened
- [ ] create a list of stadiums sorted by seating capacity
- [ ] create a list of stadiums sorted by park typology.
- [ ] Connect the output of the various sorts to the GUI #34 
- [ ] Implement a date class #37
- [ ] Implement a heap sort #39
### Definition Of Done
- [ ] Sort algorithm faster than O(n^2).
- [ ] Have the option to sort by or to filter by only certain types of stadiums.
- [ ] Include big-oh notation of sort in paragraph about big-oh notation in our project.
- [ ] Display results on in a table inside the GUI with the ability to switch between sorts
### Test Scenarios
- Need test scenarios
