### ISSUE TITLE
Dijkstra’s algorithm

### ISSUE THREAD

**Issue by notsarah** [theozornelas/throw-catch#29]
As a team member, I want to be able to find the shortest path to all stadiums starting at a certain point.
### Tasks
- [ ] Implement Dijkstra’s algorithm  To find the shortest path to all stadiums#29 
### Definition Of Done
- [ ] use Dijkstra’s algorithm 
- [ ] Algorithm produces the shortest route
### Test Scenarios
- Test Shortestbefthm again.
