### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#3]
As a baseball fan, I want a very readable, easy-to-use application to plan my dream vacation to baseball stadiums.
### Description

Create an friendly user-interface that allows the baseball fan to choose to plan a trip, take a trip, and purchase souvenirs while on the trip to stadiums. While planning a trip, the program should provide the options to design a trip based off shortest distance or travel to all stadiums (starting at Dodger stadium). On the admin side of the interface, the admin will have the following ability: modify stadiums' information, add a new team, modify (add/delete/change) the souvenirs list and the corresponding price. Admin should be able to view the total revenue for each stadium, including a grand total for all the stadiums. Both admin and baseball fan should be able to access any baseball stadium information.
### Tasks
- [x] Create an admin login #33 
- [x] Create a modify souvenirs, add souvenirs, remove souvenirs, add stadiums, add new team pages (adminstration only). #18 #28 
- [x] Create a plan trip, take a trip, purchase/shopping cart pages for baseball fan. #31 
- [x] Create a view stadiums info for both admin and baseball fan. #34 
- [x] Error checking for all input fields.
### Test Scenarios
- All testing is completed based off Test Plan (Test plan include input checking).
- All interactive objects a user is allowed to use (buttons, check boxes, etc...) are properly working.
- More to be added...
### Story Points (8)

We chose 8 points for this task because it requires several sub-tasks to complete the final task. Such as, creating a sketch/design of the GUI to ensuring all signals and slots are working. This requirement links to requirement 21, 23, and 2.
