### ISSUE TITLE
GUI for admin login

### ISSUE THREAD

**Issue by notsarah** [theozornelas/throw-catch#33]
As a baseball manager, I want to be able to access an admin only section to be able to manage the program. 
### Tasks
- [x] Create a login screen in the the GUI
- [x] Display admin screen in the GUI
- [x] create souvenir class
### Definition Of Done
- [ ] admin login screen is only accessible with the proper credentials
- [ ] interface changes when logged in as admin to show additional options
- [ ] Be able to manage souvenirs for each stadium
