### ISSUE TITLE
Create Stadium class

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#4]
As a programmer, I want a stadium class to keep track of stadiums throughout the program.
### Description

Stadium class represents a national baseball stadium. It has the following attributes: stadium name, team name, seating capacity, address, typology, surface type, date opened, box office number. Along with a list of souvenirs for each stadium object. Stadium also needs method to alter/update it's souvenir list.
### Tasks
- [x] Create getters and setters for each attribute
- [x] All attributes declared.
- [ ] Each stadium object has a list of souvenirs.
### Definition of Done
- All methods needed are implemented.
- Create unit testing for all concrete/complex method(s).
- If any attribute is altered/changed, database must be updated.
- Properly document each method for Doxygen. 
### Test Scenarios
- Check if database updates altered/changed information instantly.
### Story Points (2)

This task is 2 points because this is a small task towards a bigger goal. This task will help us lead to having a list of stadiums. Fulfills requirement ...
