### ISSUE TITLE
Output The total revenue of each stadium as well as the gran total

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#52]
As a baseball Fan, I want to track the purchases I make at each of the stadiums as well as the grand total.
### Tasks
- [x] implement an attractive and easy to use GUI interface
- [x] Implement a way to store the purchases made at each stadium that is persistent
- [x] Calculate and store the revenue for each stadium from sales
- [x] Be able to display the items sold and revenue for any stadium
- [x] Be able to display the total for any stadium
- [x] Be able to display the grand total revenue for all stadiums
### Definition Of Done
- [x] GUI interface is attractive and makes sense
- [x] The sale and revenue data is persistent
- [x] The sale and revenue data is displayed upon request for any stadium in the admin section
- [x] The Grand total revenue for ALL stadiums is displayed in the admin section of the GUI
### Test Scenarios
- The user does not select any items.
- The user does not choose any stadiums.
  #
