### ISSUE TITLE
Write At least 10 Agile Stories

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#53]
As a scrum master, I want to have at least 10 stories to distribute on each sprint in order to complete the program in the given time.
### Tasks
- [x] Create stories with a description
- [x] Create stories that have task.
- [x] Give a definition of done to each of the stories.
### Definition Of Done
- [x] Stories have a description.
- [x] Stories have a list of task.
- [x] Stories have a definition of done.
