### ISSUE TITLE
Be able to modify stadium information

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#6]
As a baseball manager, I want to be able to modify a stadiums information if a team moves to a new stadium.
### Tasks
- [x] implement an attractive and easy to use GUI interface #28 
- [x] Let an admin user modify the attributes of a stadium
- [x] The changes to a stadium should be persistent
### Definition Of Done
- [x] GUI interface is attractive and easy to use
- [x] Changes to the stadiums are persistent
- [x] Only one team is associated with any one stadium
- [x] feature is only accessible by an admin user
### Test Scenarios
- Need test scenarios
