### ISSUE TITLE
Track the souvenirs purchased by baseball fans and associated revenue

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#7]
As a baseball manager, I want to track the purchases made by fans on their trips and the corresponding costs.
### Tasks
- [x] implement an attractive and easy to use GUI interface #36 
- [x] Implement a way to store the purchases made at each stadium that is persistent #3
- [x] Calculate and store the revenue for each stadium from sales
- [x] Be able to display the items sold and revenue for any stadium
- [x] Be able to display the total revenue for any stadium
- [x] Be able to display the grand total revenue for all stadiums
### Definition Of Done
- [x] GUI interface is attractive and makes sense
- [x] The sale and revenue data is persistent
- [x] The sale and revenue data is displayed upon request for any stadium in the admin section
- [x] The Grand total revenue for ALL stadiums is displayed in the admin section of the GUI
### Test Scenarios
- Need test scenarios 
  #
