### ISSUE TITLE
Visit all Major League Stadiums starting from Dodgers Stadium

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#8]
As a baseball fan, I want to be able to plan a trip to visit every major league stadium starting at Dodgers Stadium using the shortest path possible. 
### Tasks
- [x] Implement Dijkstra’s algorithm #29 
- [x] Display results in the GUI #31
### Definition Of Done
- [x] use Dijkstra’s algorithm 
- [x] Algorithm produces the shortest route
- [x] Algorithm only uses major league stadiums
- [ ] Display the final route , stadiums visited and in what order, and total mileage in the GUI
### Test Scenarios
- Need test scenarios
