### ISSUE TITLE
Able to randomly access any baseball stadium

### ISSUE THREAD

**Issue by theozornelas** [theozornelas/throw-catch#9]
As a baseball fan or baseball manager I want to be able to randomly access the information for any baseball stadium.
### Tasks
- [ ] Create a GUI interface that allows a fan or manager to see and access all current stadiums #34 
- [ ] Display information about the stadium once selected #35
### Definition Of Done
- [ ] The GUI interface is easy to use and makes sense without explanation
- [ ] The interface allows a fan or manager to access any current stadium
- [ ] Once selected the information for that stadium is displayed
### Test Scenarios
- Need test scenarios 
  #
